services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app 
      - /app/node_modules
    env_file:
      - ../backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/quantsim?schema=public
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    command: sh -c "npm install && npm run dev"

  ingestor:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ingestor
    working_dir: /usr/src/ingestor
    volumes:
      - ../ingestor:/usr/src/ingestor
      - /usr/src/ingestor/node_modules
    ports:
      - "4001:4001"
    env_file:
      - ../ingestor/.env
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - BACKEND_URL=http://backend:3000
    depends_on:
      - redis
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quantsim
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"